### ISSUE TITLE
Eliminate perf calls

### ISSUE THREAD

**Issue by Belorus** [kentcb/Genesis.Logging#1]
Hi Kent,

There is a small note in readme that perfcalls are not eliminatable as they return value.
using blocks in C# support nulls. Desugared finally block after compilation contains nullcheck.

**Comment by toseef-ajmeri** [comment]
Hi Kent,
we are using your plugin for logging in our app,
Can you please tell us, where can i find the log files,

**Comment by kentcb** [comment]
@Belorus Sorry, somehow missed this. The `using` isn't the problem - it's the `ConditionalAttribute`, which can only be used against members without return values, which makes sense because otherwise you could have code like:
```C#
var whatever = logger.Perf("foo");
Console.WriteLine(whatever);
```
And what would the compiler do here when compiling without the `LOGGING` symbol defined?

@toseef-ajmeri Please read the readme. There is no log file by default.
