### ISSUE TITLE
Lazy logging

### ISSUE THREAD

**Issue by pellet** [kentcb/Genesis.Logging#5]
I was thinking about adding some lazy logging(pass a function which returns a string) method signatures for verbose and debug levels.
This would improve efficiency for when these levels are disabled since no evaluation would occur such as calling 'ToString' on an object.
Would you be interested in a pull request?

**Comment by kentcb** [comment]
Thanks, but no. The reason these don't exist is because they encourage behavior that will perform very poorly. This:
```C#
if (logger.IsDebugEnabled)
{
    logger.Debug("Something that has substitutions {0} {1} {2}", arg0, arg1, arg2);
}
```
Does not allocate when debug is not enabled. This:
```C#
logger.DebugIf(() => "Something that has substitutions {0} {1} {2}", arg0, arg1, arg2);
```
Will allocate for the lambda _even when debug is disabled_ because it captures `arg0`, `arg1`, and `arg2`. Occasionally you might have scenarios that wouldn't capture and therefore wouldn't allocate, but those would be few and far between and then the onus would be on the consumer to understand and choose an API accordingly.

**Comment by pellet** [comment]
Hmm your right, I didn't think about the memory being captured due to it being a lambda.
I guess it's best to just pass the objects in as param references and that way ToString won't necessarily be called on them and they also won't be copied.
